env:
  global:
  - BINSTAR_USER: menpo
  matrix:
   - PYTHON_VERSION=2
     CONDA_NPY=18
   - PYTHON_VERSION=2
     CONDA_NPY=19
   - PYTHON_VERSION=3
     CONDA_NPY=18
   - PYTHON_VERSION=3
     CONDA_NPY=19

install:
- wget https://raw.githubusercontent.com/jabooth/condaci/master/condaci.py -O condaci.py
- python condaci.py setup $PYTHON_VERSION --channel $BINSTAR_USER
- export PATH=$HOME/miniconda/bin:$PATH

script:
- python condaci.py auto ./conda --binstaruser $BINSTAR_USER --binstarkey $BINSTAR_KEY --pypiuser $PYPI_USERNAME  --pypipassword $PYPI_PASSWORD

notifications:
  email: false
  flowdock: 769202b66114a5ce0e61df484dfeb177
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
